//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 ShadowPack.rc 使用
//
#define IDCANCEL                        2
#define IDM_ABOUTBOX                    0x0010
#define IDM_CONFIGBOX                   0x0020
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SHADOWPACK_DIALOG           102
#define IDS_COLUMN_NAME                 102
#define IDS_COLUMN_TIME                 103
#define IDS_COLUMN_SIZE                 104
#define IDS_READ_FILE                   105
#define IDS_LOAD_DATA                   106
#define IDS_SAVE_DATA                   107
#define IDS_FILL_EMPTY_SPACE            108
#define IDS_WRITE_FILE                  109
#define IDS_EXPORT_DATA                 110
#define IDS_CHANGED_SAVE                111
#define IDS_PASSWORD_CAN_NOT_NULL       112
#define IDS_PASSWORD_CAN_NOT_MATCH      113
#define IDS_OPTIONS                     114
#define IDS_EMPTY_PACK                  115
#define IDS_INVALID_HEADER              116
#define IDS_BPB                         116
#define IDS_OPT_PIXEL_MEDIA             117
#define IDS_OPT_PIXEL_MEDIA_BLOCK_UNIT  118
#define IDS_OPT_COFF_MEDIA              119
#define IDS_OPT_COFF_MEDIA_BLOCK_UNIT   120
#define IDS_CIPHER_NONE                 121
#define IDS_CIPHER_AES                  122
#define IDS_CIPHER_SEED                 123
#define IDS_CIPHER_CAMELLIA             124
#define IDS_CIPHER_BLOWFISH             125
#define IDS_CIPHER_CAST                 126
#define IDS_CIPHER_IDEA                 127
#define IDR_MAINFRAME                   128
#define IDS_CIPHER_RC4                  128
#define IDD_DIALOG_PASSWORD             129
#define IDS_CIPHER_3DES                 129
#define IDS_CONFIGBOX                   130
#define IDD_PROPPAGE_BMP_FILE           131
#define IDS_HD_PATH_CAN_NOT_NULL        131
#define IDS_CACHE_PATH_CAN_NOT_NULL     131
#define IDS_RELOAD_CONFIG               132
#define IDD_PROPPAGE_PNG_FILE           133
#define IDD_PROPPAGE_BYTE_PER_BLOCK_MEDIA 134
#define IDD_PROPPAGE_JPEG_FILE          135
#define IDD_PROPPAGE_TIFF_FILE          136
#define IDD_PROPPAGE_PPM_FILE           137
#define IDD_CONFIGBOX                   138
#define IDS_PE_CANCELED                 400
#define IDS_PE_IO                       401
#define IDS_PE_CORRUPT_DATA             402
#define IDS_PE_CIPHER                   403
#define IDS_PE_OVER_CAPICITY            404
#define IDS_PE_UNSUPPORT_PACK           405
#define IDS_PE_UNSUPPORT_MEDIA          406
#define IDS_PE_EXISTED                  407
#define IDS_PE_NOMEM                    408
#define IDS_PE_INTERNAL                 409
#define IDS_LOCALE_UNKNOWN              599
#define IDS_LOCALE_CHINESE_SC           600
#define IDS_LOCALE_ENGLISH_US           601
#define IDC_LIST_DATA                   1000
#define IDC_BFSIZE                      1000
#define IDC_BTN_ITEM_DELETE             1001
#define IDC_BFOFFBITS                   1001
#define IDC_BTN_ITEM_ADD                1002
#define IDC_BIWIDTH                     1002
#define IDC_BTN_ITEM_CLEAR_ALL          1003
#define IDC_BIHEIGTH                    1003
#define IDC_BTN_ITEM_EXPORT             1004
#define IDC_BIBITCOUNT                  1004
#define IDC_BICOMPRESSION               1005
#define IDC_BTN_MEDIA_OPEN              1006
#define IDC_BIXPELSPERMETER             1006
#define IDC_IMAGE_CAPICITY              1007
#define IDC_BIYPELSPERMETER             1007
#define IDC_BTN_MEDIA_CLOSE             1008
#define IDC_COMBO_CRYPTO                1008
#define IDC_BTN_MEDIA_SAVE              1009
#define IDC_BTN_MEDIA_OPTION            1013
#define IDC_STATIC_TOTAL_BYTE           1013
#define IDC_EDIT_PASSWD1                1014
#define IDC_PROGRESS                    1015
#define IDC_INFO_CAPICITY               1016
#define IDC_STATIC_USED_BYTE            1016
#define IDC_INFO_FOOTER                 1017
#define IDC_MFCLINK1                    1017
#define IDC_MFCLINK                     1017
#define IDC_EDIT_PASSWD2                1018
#define IDC_BTN_CANCEL                  1019
#define IDC_EDIT_PASSWORD               1020
#define IDC_JPEG_IMAGE_WIDTH            1025
#define IDC_JPEG_IMAGE_HEIGHT           1026
#define IDC_JPEG_NUM_COMP               1027
#define IDC_JPEG_COLOR_SPACE            1028
#define IDC_JPEG_JFIF_MAJOR             1029
#define IDC_JPEG_JFIF_MINOR             1030
#define IDC_JPEG_DENSITY_UNIT           1031
#define IDC_JPEG_X_DENSITY              1032
#define IDC_JPEG_Y_DENSITY              1033
#define IDC_RADIO_1BP1B                 1034
#define IDC_RADIO_1BP2B                 1035
#define IDC_RADIO_1BP3B                 1036
#define IDC_RADIO_1BP4B                 1037
#define IDC_PNG_WIDTH                   1038
#define IDC_PNG_HEIGHT                  1039
#define IDC_PNG_BIT_DEPTH               1040
#define IDC_PNG_COLOR_TYPE              1041
#define IDC_PNG_INTERLACE_TYPE          1042
#define IDC_PNG_COMPRESSION_TYPE        1043
#define IDC_PNG_FILTER_TYPE             1044
#define IDC_PNG_BIT_DEPTH2              1045
#define IDC_TIFF_TIFFTAG_YRESOLUTION    1045
#define IDC_PNG_CHANNELS                1046
#define IDC_TIFF_TIFFTAG_RESOLUTIONUNIT 1047
#define IDC_TIFF_TIFFTAG_EXTRASAMPLES   1048
#define IDC_JPEG_TIFFTAG_IMAGELENGTH    1049
#define IDC_TIFF_TIFFTAG_IMAGELENGTH    1049
#define IDC_TIFF_TIFFTAG_IMAGEWIDTH     1050
#define IDC_TIFF_TIFFTAG_COMPRESSION    1051
#define IDC_TIFF_TIFFTAG_SAMPLESPERPIXEL 1052
#define IDC_TIFF_TIFFTAG_BITSPERSAMPLE  1053
#define IDC_TIFF_TIFFTAG_PHOTOMETRIC    1054
#define IDC_TIFF_TIFFTAG_PLANARCONFIG   1055
#define IDC_TIFF_TIFFTAG_XRESOLUTION    1056
#define IDC_PPM_IMAGE_WIDTH             1057
#define IDC_PPM_IMAGE_HEIGHT            1058
#define IDC_PPM_IMAGE_FORMAT            1059
#define IDC_COMBO_LANG                  1060
#define IDC_CHECK_MEDIA_HD_CACHE        1061
#define IDC_CHECK_PACK_HD_CACHE         1062
#define IDC_BTN_SEL_MEDIA_HD_CACHE      1063
#define IDC_BTN_SEL_PACK_HD_CACHE       1064
#define IDC_CHECK_MEDIA_HD_CACHE_USE_TMP 1065
#define IDC_CHECK_PACK_HD_CACHE_USE_TMP 1066
#define IDC_STATIC_MEDIA_TEMP_DIR       1067
#define IDC_STATIC_PACK_TEMP_DIR        1069
#define IDC_STATIC_PACK_CUSTOM_TEMP_DIR 1070
#define IDC_STATIC_MEDIA_CUSTOM_TEMP_DIR 1078

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1071
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
