/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n4.5-dev-3529-ga66b58d61c-20220117"
#endif /* AVUTIL_FFVERSION_H */
